import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Spinner from "@/components/Spinner";
import Session from "@/components/Session";
import { Poppins } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add the required font weights
  variable: "--font-poppins", // Optional: Define a CSS variable
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "NDMS-eduHub",
  description: "Generated by create next app",
};

import { getServerSession } from "next-auth";

export default async function RootLayout({ children }) {
  // const session = await getServerSession();
  // console.log("sss:", session);
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.variable} antialiased `}
      >
        <Suspense fallback={<Spinner />}>
          <Session>{children}</Session>
        </Suspense>
      </body>
    </html>
  );
}
